Fix bug: double click on composite node in package view failed
Error was:
Traceback (most recent call last):
  File "${OPENALEA_SRC}/oalab/src/openalea/oalab/package/treeview.py", line 40, in mouseDoubleClickEvent
    cat, fn = applet.add(applet.project(), obj.name + '.wpy', obj, category='model', dtype='Workflow')
  File "${OPENALEA_SRC}/oalab/src/openalea/oalab/gui/container.py", line 342, in add
    data = project.add(category=category, filename=filename, content=code, dtype=dtype)
  File "${OPENALEA_SRC}/core/src/core/project/project.py", line 230, in add
    return self.add_item(category, obj, **kwargs)
  File "${OPENALEA_SRC}/core/src/core/project/project.py", line 336, in add_item
    data = self._add_item(category, obj, **kwargs)
  File "${OPENALEA_SRC}/core/src/core/project/project.py", line 305, in _add_item
    data_obj = DataFactory(new_path, mimetype, dtype=dtype, default_content=content)
  File "${OPENALEA_SRC}/core/src/core/service/data.py", line 123, in DataFactory
    f.write(default_content)
TypeError: must be convertible to a buffer, not CompositeNodeFactory